/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-06-08 18:57:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.logado;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class indexlogado_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1464835410000L));
    _jspx_dependants.put("jar:file:/C:/Users/Hiro/Desktop/workspaceprojeto/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/financial_health/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098721890000L));
    _jspx_dependants.put("jar:file:/C:/Users/Hiro/Desktop/workspaceprojeto/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/financial_health/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098721890000L));
    _jspx_dependants.put("jar:file:/C:/Users/Hiro/Desktop/workspaceprojeto/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/financial_health/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098721890000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Arquivos de folha de estilo CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/financial_health/css/bootstrap.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/financial_health/css/bootstrap-theme.min.css\"/>\r\n");
      out.write("<!-- Arquivos Javascript -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/financial_health/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/financial_health/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"container\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-md-12\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/template/topo.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mensagem}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t<div class=\"col-md-3 panel text-center\">\r\n");
      out.write("\t\t\t<a href=\"#\" data-target=\"#janelainvestimento\" data-toggle=\"modal\" class=\"btn btn-default btn-block\">Cadastrar Investimento</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3 panel text-center\">\r\n");
      out.write("\t\t\t<a href=\"#\" data-target=\"#janeladespesafixa\" data-toggle=\"modal\" class=\"btn btn-default btn-block\">Cadastrar Despesa Fixa</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3 panel text-center\">\r\n");
      out.write("\t\t\t<a href=\"#\" data-target=\"#janeladespesavariavel\" data-toggle=\"modal\" class=\"btn btn-default btn-block\">Cadastrar Despesa Variavel</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<br/><br/><br/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3 panel text-center\">\r\n");
      out.write("\t\t\t<a href=\"/financial_health/logado/analise.jsp\" class=\"btn btn-default btn-block\" >Busca/Periodo</a> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3 panel text-center\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"btn btn-default btn-block\" >Estimativa</a> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t <div class=\"col-md-3 panel text-center\"> \r\n");
      out.write("\t \t\t<a href=\"/financial_health/ControleUsuario?action=logout\" class=\"btn btn-danger btn-block\">\r\n");
      out.write("\t \t\t\t<span class=\"glyphicon glyphicon-off\"></span> Logout\r\n");
      out.write("\t \t\t</a>\r\n");
      out.write("\t  \t </div> \r\n");
      out.write("\t\r\n");
      out.write("\t<hr/>\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"janelainvestimento\" class=\"modal fade\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header bg-default\">\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-user\"></span>\r\n");
      out.write("\t\t\t\t\t\tCadastrar Investimento\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tPreencha os campos abaixo para registrar:\r\n");
      out.write("\t\t\t\t\t<hr/>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<form name=\"formularioinvestimento\" method=\"post\" action=\"/financial_health/ControleInvestimento?action=cadastrar\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<label>Nome do Investimento</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"nome\" class=\"form-control\" placeholder=\"Digite aqui\"/>\r\n");
      out.write("\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t<label>Valor:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"number\" name=\"valor\" class=\"form-control\" placeholder=\"Digite aqui\"/>\r\n");
      out.write("\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<label>Data do Investimento</label><br/>\r\n");
      out.write("\t\t\t\t\t\t<input  type=\"date\" name=\"datainvestimento\" class=\"form-control required\" />\r\n");
      out.write("\t\t\t\t\t\t<br/><br/>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Cadastrar\" class=\"btn btn-success\" />\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div id=\"janeladespesafixa\" class=\"modal fade\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header bg-default\">\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-user\"></span>\r\n");
      out.write("\t\t\t\t\t\tCadastrar Despesa Fixa\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tPreencha os campos abaixo para registrar:\r\n");
      out.write("\t\t\t\t\t<hr/>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<form name=\"formulariodespesafixa\" method=\"post\" action=\"/financial_health/ControleDespesaFixa?action=cadastrar\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<label>Nome da Despesa</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"nome\" class=\"form-control\" placeholder=\"Digite aqui\"/>\r\n");
      out.write("\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t<label>Valor:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"number\" name=\"valor\" class=\"form-control\" placeholder=\"Digite aqui\"/>\r\n");
      out.write("\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<label>Data da Despesa</label><br/>\r\n");
      out.write("\t\t\t\t\t\t<input  type=\"date\" name=\"datadespesafixa\" class=\"form-control required\" />\r\n");
      out.write("\t\t\t\t\t\t<br/><br/>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Cadastrar\" class=\"btn btn-success\" />\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div id=\"janeladespesavariavel\" class=\"modal fade\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header bg-default\">\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-user\"></span>\r\n");
      out.write("\t\t\t\t\t\tCadastrar Despesa Variavel\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tPreencha os campos abaixo para registrar:\r\n");
      out.write("\t\t\t\t\t<hr/>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<form name=\"formulariodespesavariavel\" method=\"post\" action=\"/financial_health/ControleDespesaVariavel?action=cadastrar\">\r\n");
      out.write("\t\t\t\t\t\t<label>Nome da Despesa</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"nome\" class=\"form-control\" placeholder=\"Digite aqui\"/>\r\n");
      out.write("\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t<label>Valor:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"number\" name=\"valor\" class=\"form-control\" placeholder=\"Digite aqui\"/>\r\n");
      out.write("\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<label>Data da Despesa</label><br/>\r\n");
      out.write("\t\t\t\t\t\t<input  type=\"date\" name=\"datadespesavariavel\" class=\"form-control required\" />\r\n");
      out.write("\t\t\t\t\t\t<br/><br/>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Cadastrar\" class=\"btn btn-success\" />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
